### ISSUE TITLE
Missing EML file in SOS generated Darwin Core Archives

### ISSUE THREAD

**Issue by shahmanash** [biodiversitydata-se/SOS#5]
The following datasets generated by SOS do not contain EML files.

```
  "name": "SHARK.dwca.zip",
  "created": "2021-07-01T15:40:15+02:00",
  "size": 127349887,

  "name": "VirtualHerbarium.dwca.zip",
  "created": "2021-06-30T16:40:56+02:00",
  "size": 184300531,

  "name": "Fishdata2.dwca.zip",
  "created": "2021-06-18T07:55:01+02:00",
  "size": 48617,

  "name": "ClamGateway.dwca.zip",
  "created": "2021-07-01T15:39:39+02:00",
  "size": 1318031,

  "name": "MVM.dwca.zip",
  "created": "2021-06-30T16:40:30+02:00",
  "size": 90599499,
```
Guide on DarwinCore archive
https://github.com/gbif/ipt/wiki/DwCAHowToGuide

Guide on metadata
https://github.com/gbif/ipt/wiki/GMPHowToGuide

As SOS is adding the EML file manually
https://github.com/gbif/ipt/wiki/GMPHowToGuide#publishing-metadata-manually

Tool to validate EML file
https://tools.gbif.org/dwca-validator/eml.do

**Comment by Adbmnk** [comment]
The EML files is now added to the archive.
